# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from quadrotor_msgs/ReplanState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import geometry_msgs.msg
import nav_msgs.msg
import quadrotor_msgs.msg
import std_msgs.msg

class ReplanState(genpy.Message):
  _md5sum = "38714edcd5022172624012c3dbfdd606"
  _type = "quadrotor_msgs/ReplanState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# all information for a replan

Header header

int16 state
float64[] iniState
nav_msgs/Odometry target
quadrotor_msgs/OccMap3d occmap

# other temporal variables
float64[] path
time replan_stamp
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: nav_msgs/Odometry
# This represents an estimate of a position and velocity in free space.  
# The pose in this message should be specified in the coordinate frame given by header.frame_id.
# The twist in this message should be specified in the coordinate frame given by the child_frame_id
Header header
string child_frame_id
geometry_msgs/PoseWithCovariance pose
geometry_msgs/TwistWithCovariance twist

================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/TwistWithCovariance
# This expresses velocity in free space with uncertainty.

Twist twist

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3 linear
Vector3 angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: quadrotor_msgs/OccMap3d
Header header

float32 resolution
int16 size_x
int16 size_y
int16 size_z
int16 offset_x
int16 offset_y
int16 offset_z

int8[] data"""
  __slots__ = ['header','state','iniState','target','occmap','path','replan_stamp']
  _slot_types = ['std_msgs/Header','int16','float64[]','nav_msgs/Odometry','quadrotor_msgs/OccMap3d','float64[]','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,state,iniState,target,occmap,path,replan_stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ReplanState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.state is None:
        self.state = 0
      if self.iniState is None:
        self.iniState = []
      if self.target is None:
        self.target = nav_msgs.msg.Odometry()
      if self.occmap is None:
        self.occmap = quadrotor_msgs.msg.OccMap3d()
      if self.path is None:
        self.path = []
      if self.replan_stamp is None:
        self.replan_stamp = genpy.Time()
    else:
      self.header = std_msgs.msg.Header()
      self.state = 0
      self.iniState = []
      self.target = nav_msgs.msg.Odometry()
      self.occmap = quadrotor_msgs.msg.OccMap3d()
      self.path = []
      self.replan_stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.state
      buff.write(_get_struct_h().pack(_x))
      length = len(self.iniState)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.iniState))
      _x = self
      buff.write(_get_struct_3I().pack(_x.target.header.seq, _x.target.header.stamp.secs, _x.target.header.stamp.nsecs))
      _x = self.target.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.target.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.target.pose.pose.position.x, _x.target.pose.pose.position.y, _x.target.pose.pose.position.z, _x.target.pose.pose.orientation.x, _x.target.pose.pose.orientation.y, _x.target.pose.pose.orientation.z, _x.target.pose.pose.orientation.w))
      buff.write(_get_struct_36d().pack(*self.target.pose.covariance))
      _x = self
      buff.write(_get_struct_6d().pack(_x.target.twist.twist.linear.x, _x.target.twist.twist.linear.y, _x.target.twist.twist.linear.z, _x.target.twist.twist.angular.x, _x.target.twist.twist.angular.y, _x.target.twist.twist.angular.z))
      buff.write(_get_struct_36d().pack(*self.target.twist.covariance))
      _x = self
      buff.write(_get_struct_3I().pack(_x.occmap.header.seq, _x.occmap.header.stamp.secs, _x.occmap.header.stamp.nsecs))
      _x = self.occmap.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f6h().pack(_x.occmap.resolution, _x.occmap.size_x, _x.occmap.size_y, _x.occmap.size_z, _x.occmap.offset_x, _x.occmap.offset_y, _x.occmap.offset_z))
      length = len(self.occmap.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(struct.Struct(pattern).pack(*self.occmap.data))
      length = len(self.path)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.path))
      _x = self
      buff.write(_get_struct_2I().pack(_x.replan_stamp.secs, _x.replan_stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.target is None:
        self.target = nav_msgs.msg.Odometry()
      if self.occmap is None:
        self.occmap = quadrotor_msgs.msg.OccMap3d()
      if self.replan_stamp is None:
        self.replan_stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 2
      (self.state,) = _get_struct_h().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.iniState = s.unpack(str[start:end])
      _x = self
      start = end
      end += 12
      (_x.target.header.seq, _x.target.header.stamp.secs, _x.target.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.target.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target.child_frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.target.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.target.pose.pose.position.x, _x.target.pose.pose.position.y, _x.target.pose.pose.position.z, _x.target.pose.pose.orientation.x, _x.target.pose.pose.orientation.y, _x.target.pose.pose.orientation.z, _x.target.pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 288
      self.target.pose.covariance = _get_struct_36d().unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.target.twist.twist.linear.x, _x.target.twist.twist.linear.y, _x.target.twist.twist.linear.z, _x.target.twist.twist.angular.x, _x.target.twist.twist.angular.y, _x.target.twist.twist.angular.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 288
      self.target.twist.covariance = _get_struct_36d().unpack(str[start:end])
      _x = self
      start = end
      end += 12
      (_x.occmap.header.seq, _x.occmap.header.stamp.secs, _x.occmap.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.occmap.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.occmap.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.occmap.resolution, _x.occmap.size_x, _x.occmap.size_y, _x.occmap.size_z, _x.occmap.offset_x, _x.occmap.offset_y, _x.occmap.offset_z,) = _get_struct_f6h().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.occmap.data = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.path = s.unpack(str[start:end])
      _x = self
      start = end
      end += 8
      (_x.replan_stamp.secs, _x.replan_stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      self.replan_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.state
      buff.write(_get_struct_h().pack(_x))
      length = len(self.iniState)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.iniState.tostring())
      _x = self
      buff.write(_get_struct_3I().pack(_x.target.header.seq, _x.target.header.stamp.secs, _x.target.header.stamp.nsecs))
      _x = self.target.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.target.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.target.pose.pose.position.x, _x.target.pose.pose.position.y, _x.target.pose.pose.position.z, _x.target.pose.pose.orientation.x, _x.target.pose.pose.orientation.y, _x.target.pose.pose.orientation.z, _x.target.pose.pose.orientation.w))
      buff.write(self.target.pose.covariance.tostring())
      _x = self
      buff.write(_get_struct_6d().pack(_x.target.twist.twist.linear.x, _x.target.twist.twist.linear.y, _x.target.twist.twist.linear.z, _x.target.twist.twist.angular.x, _x.target.twist.twist.angular.y, _x.target.twist.twist.angular.z))
      buff.write(self.target.twist.covariance.tostring())
      _x = self
      buff.write(_get_struct_3I().pack(_x.occmap.header.seq, _x.occmap.header.stamp.secs, _x.occmap.header.stamp.nsecs))
      _x = self.occmap.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f6h().pack(_x.occmap.resolution, _x.occmap.size_x, _x.occmap.size_y, _x.occmap.size_z, _x.occmap.offset_x, _x.occmap.offset_y, _x.occmap.offset_z))
      length = len(self.occmap.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(self.occmap.data.tostring())
      length = len(self.path)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.path.tostring())
      _x = self
      buff.write(_get_struct_2I().pack(_x.replan_stamp.secs, _x.replan_stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.target is None:
        self.target = nav_msgs.msg.Odometry()
      if self.occmap is None:
        self.occmap = quadrotor_msgs.msg.OccMap3d()
      if self.replan_stamp is None:
        self.replan_stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 2
      (self.state,) = _get_struct_h().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.iniState = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 12
      (_x.target.header.seq, _x.target.header.stamp.secs, _x.target.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.target.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target.child_frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.target.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.target.pose.pose.position.x, _x.target.pose.pose.position.y, _x.target.pose.pose.position.z, _x.target.pose.pose.orientation.x, _x.target.pose.pose.orientation.y, _x.target.pose.pose.orientation.z, _x.target.pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 288
      self.target.pose.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 48
      (_x.target.twist.twist.linear.x, _x.target.twist.twist.linear.y, _x.target.twist.twist.linear.z, _x.target.twist.twist.angular.x, _x.target.twist.twist.angular.y, _x.target.twist.twist.angular.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 288
      self.target.twist.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 12
      (_x.occmap.header.seq, _x.occmap.header.stamp.secs, _x.occmap.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.occmap.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.occmap.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.occmap.resolution, _x.occmap.size_x, _x.occmap.size_y, _x.occmap.size_z, _x.occmap.offset_x, _x.occmap.offset_y, _x.occmap.offset_z,) = _get_struct_f6h().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.occmap.data = numpy.frombuffer(str[start:end], dtype=numpy.int8, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.path = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 8
      (_x.replan_stamp.secs, _x.replan_stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      self.replan_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_36d = None
def _get_struct_36d():
    global _struct_36d
    if _struct_36d is None:
        _struct_36d = struct.Struct("<36d")
    return _struct_36d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
_struct_f6h = None
def _get_struct_f6h():
    global _struct_f6h
    if _struct_f6h is None:
        _struct_f6h = struct.Struct("<f6h")
    return _struct_f6h
_struct_h = None
def _get_struct_h():
    global _struct_h
    if _struct_h is None:
        _struct_h = struct.Struct("<h")
    return _struct_h
